import type { ReactiveSceneId } from "../../core/reactive-state/types";
import type { AetherScene } from "./sceneTypes";

export const AETHER_SCENES: AetherScene[] = [
  {
    id: "deep-sky",
    name: "Deep Sky",
    chineseName: "深空回响",
    description: "安静的蓝色深度，低频把远方的星尘推近。",
    label: "SOFT / SPATIAL",
    palette: { sky: "#050917", horizon: "#142d58", accent: "#73c9ff", secondary: "#9eb8ff", glow: "#305ca9", ink: "#edf8ff" },
    wallpaper: { density: 0.8, drift: 0.22, depth: 0.9 },
    audioResponse: { bassScale: 1.25, midScale: 0.72, trebleScale: 0.9, onsetAccent: 0.7 },
    albumCoverMode: "procedural",
    aura: { intensity: 0.34, edgeFlow: 0.26 },
    overlays: { stars: true, horizonGlow: true, grain: 0.08 },
    motionProfile: "slow",
    performanceProfile: "balanced",
  },
  {
    id: "blue-hour",
    name: "Blue Hour",
    chineseName: "蓝调时刻",
    description: "天色将暗未暗，窗口与音乐一起留下柔和边缘。",
    label: "WINDOW / AURA",
    palette: { sky: "#081225", horizon: "#3d3c85", accent: "#9ec7ff", secondary: "#d3bfff", glow: "#6458c7", ink: "#f3f6ff" },
    wallpaper: { density: 0.6, drift: 0.42, depth: 0.68 },
    audioResponse: { bassScale: 0.94, midScale: 1.0, trebleScale: 0.82, onsetAccent: 0.62 },
    albumCoverMode: "metadata",
    aura: { intensity: 0.58, edgeFlow: 0.5 },
    overlays: { stars: true, horizonGlow: true, grain: 0.1 },
    motionProfile: "balanced",
    performanceProfile: "balanced",
  },
  {
    id: "white-silence",
    name: "White Silence",
    chineseName: "白色静默",
    description: "音乐停下时不熄灭，只把反应收束成一层呼吸。",
    label: "QUIET / CLEAN",
    palette: { sky: "#b7d6e5", horizon: "#eaf7f1", accent: "#ffffff", secondary: "#9bc6d7", glow: "#e6fff5", ink: "#09202e" },
    wallpaper: { density: 0.35, drift: 0.12, depth: 0.42 },
    audioResponse: { bassScale: 0.65, midScale: 0.58, trebleScale: 0.42, onsetAccent: 0.3 },
    albumCoverMode: "generic",
    aura: { intensity: 0.22, edgeFlow: 0.18 },
    overlays: { stars: false, horizonGlow: true, grain: 0.04 },
    motionProfile: "slow",
    performanceProfile: "eco",
  },
  {
    id: "gold-pulse",
    name: "Gold Pulse",
    chineseName: "金色脉冲",
    description: "鼓点来时让暖金色穿过深蓝，而不是把整块屏幕点亮。",
    label: "RHYTHM / WARM",
    palette: { sky: "#100d17", horizon: "#4b2d3b", accent: "#f3c878", secondary: "#ff9f75", glow: "#9a6041", ink: "#fff7e6" },
    wallpaper: { density: 0.7, drift: 0.68, depth: 0.76 },
    audioResponse: { bassScale: 1.46, midScale: 1.04, trebleScale: 1.08, onsetAccent: 1.0 },
    albumCoverMode: "procedural",
    aura: { intensity: 0.46, edgeFlow: 0.58 },
    overlays: { stars: true, horizonGlow: true, grain: 0.12 },
    motionProfile: "dynamic",
    performanceProfile: "quality",
  },
  {
    id: "album-immersion",
    name: "Album Immersion",
    chineseName: "专辑沉浸",
    description: "让当前音频的色彩成为整个桌面的软光源。",
    label: "COVER / LIVING",
    palette: { sky: "#10111b", horizon: "#443457", accent: "#d6b8ff", secondary: "#86e1d5", glow: "#8b65af", ink: "#faf4ff" },
    wallpaper: { density: 0.9, drift: 0.36, depth: 0.84 },
    audioResponse: { bassScale: 1.12, midScale: 1.28, trebleScale: 1.18, onsetAccent: 0.76 },
    albumCoverMode: "metadata",
    aura: { intensity: 0.52, edgeFlow: 0.38 },
    overlays: { stars: true, horizonGlow: true, grain: 0.09 },
    motionProfile: "balanced",
    performanceProfile: "balanced",
  },
];

export function getScene(id: ReactiveSceneId): AetherScene {
  return AETHER_SCENES.find((scene) => scene.id === id) ?? AETHER_SCENES[0];
}
